export const SREACH_FOCUS = "search_focus"
export const SREACH_BLUR = "search_blur"
//export const GETLIST = "getlist"
export const CHANGE_LIST = "changelist"
export const MOUSE_ENTER = "mouse_enter"
export const MOUSE_LEAVE = "mouseleave"
export const CHANGE_PAGE = "change_page"